version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: nouchka/sqlite:latest
    container_name: sqlite_db
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
